# Bagian Penjelasan Kode Program Hill Cipher (Encrypt & Decrypt)

Pada Program ini saya menggunakan Matrix 2x2 sebagai kunci dan plain teks yang memiliki jumlah huruf berkelipatan 2

Referensi : <br>
https://journal.uii.ac.id/Snati/article/view/6245/5618 <br>
https://www.youtube.com/watch?v=mlUoYUzakPw <br>
https://www.youtube.com/watch?v=XCPC30TYfqw <br>

<b>Fadhlan S. J. (1203210064)</b>

In [1]:
import numpy as np
#Menggunakan Library Numpy

In [2]:
Plain = "Hill Cipher"
Plain
# Input teks yang akan di Enkripsi

'Hill Cipher'

In [3]:
Plain = Plain.lower().replace(" ","")
Plain

'hillcipher'

In [4]:
Key = "test"
Key
if len(Plain) % 2 != 0:
    Plain+='x'
    #Bila total huruf pada plain teks tidak termasuk kelipatan 2, maka akan menambahkan satu huruf x
# Memasukkan key sebagai kunci untuk enkripsi & dekripsi

In [5]:
EAM = {chr(i):i-97 for i in range(97, 97+26)}
print(EAM)
# Mengacu pada ASCII, mengambil nilai a-z (dimulai dari 0 sampai 25)

{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o': 14, 'p': 15, 'q': 16, 'r': 17, 's': 18, 't': 19, 'u': 20, 'v': 21, 'w': 22, 'x': 23, 'y': 24, 'z': 25}


In [6]:
EAM_rev = {i-97:chr(i) for i in range(97, 97+26)}
print(EAM_rev)
# hanyak membalik saja untuk mengubah angka menjadi huruf kembali

{0: 'a', 1: 'b', 2: 'c', 3: 'd', 4: 'e', 5: 'f', 6: 'g', 7: 'h', 8: 'i', 9: 'j', 10: 'k', 11: 'l', 12: 'm', 13: 'n', 14: 'o', 15: 'p', 16: 'q', 17: 'r', 18: 's', 19: 't', 20: 'u', 21: 'v', 22: 'w', 23: 'x', 24: 'y', 25: 'z'}


In [7]:
Plain_number = [EAM[i] for i in Plain]
Plain_number

# mengubah tiap huruf pada teks plain menjadi nomor

[7, 8, 11, 11, 2, 8, 15, 7, 4, 17]

In [8]:
key_number = [EAM[i] for i in Key]
key_number
# mengubah tiap huruf key menjadi nomor

[19, 4, 18, 19]

In [9]:
# if len(key_number) % 2 == 0:
#     divider = 2
# else:
#     divider = 3
BL = len(key_number)// 2
# BL = len(key_number) // divider
# Digunakan untuk menjadikan sebuah array menyesuaikan dengan len dari key number

In [10]:
key_matrix = np.array(key_number).reshape(BL, BL)
key_matrix

# Mengubah key number menjadi key matriks 2x2

array([[19,  4],
       [18, 19]])

In [11]:
Plain_array = np.array(Plain_number)
Plain_array
#Membuat Plain number tadi menjadi plain array

array([ 7,  8, 11, 11,  2,  8, 15,  7,  4, 17])

In [12]:
plain_block = np.split(Plain_array, len(Plain_array)/BL)
plain_block
#Membuat plain block yang memiliki nilai dari plain array dibagi menjadi 2 nilai per array, digunakan untuk mengkalkulasi pada rumus

[array([7, 8]),
 array([11, 11]),
 array([2, 8]),
 array([15,  7]),
 array([ 4, 17])]

In [13]:
CT_blocks = [np.matmul(plain_block[i], key_matrix) % 26 for i in range(len(plain_block))]
CT_blocks
#Melakukan perhitungan setiap 2 kata/angka yang sudah di split tadi

[array([17, 24], dtype=int32),
 array([17, 19], dtype=int32),
 array([0, 4], dtype=int32),
 array([21, 11], dtype=int32),
 array([18,  1], dtype=int32)]

In [14]:
CT_array = np.concatenate(CT_blocks)
CT_array

array([17, 24, 17, 19,  0,  4, 21, 11, 18,  1], dtype=int32)

In [15]:
CT = [EAM_rev[CT_array[i]] for i in range(len(CT_array))]
CT

['r', 'y', 'r', 't', 'a', 'e', 'v', 'l', 's', 'b']

In [16]:
''.join(CT)

'ryrtaevlsb'

In [17]:
np.linalg.inv(key_matrix)

array([[ 0.06574394, -0.01384083],
       [-0.06228374,  0.06574394]])

In [18]:
round(np.linalg.det(key_matrix))

289

In [19]:
adj_key_matrix = np.linalg.inv(key_matrix) * round(np.linalg.det(key_matrix))
adj_key_matrix

array([[ 19.,  -4.],
       [-18.,  19.]])

In [20]:
key_inverse = (9 * adj_key_matrix) % 26
key_inverse

array([[15., 16.],
       [20., 15.]])

In [21]:
CT_number = [EAM[i] for i in CT]
CT_number

[17, 24, 17, 19, 0, 4, 21, 11, 18, 1]

In [22]:
CT_array = np.array(CT_number)
CT_array

array([17, 24, 17, 19,  0,  4, 21, 11, 18,  1])

In [23]:
CT_blocks = np.split(CT_array, len(CT_number)//BL)
CT_blocks

[array([17, 24]),
 array([17, 19]),
 array([0, 4]),
 array([21, 11]),
 array([18,  1])]

In [24]:
PT_blocks = [np.matmul(CT_blocks[i], key_inverse) % 26 for i in range(len(CT_blocks))]
PT_blocks

[array([7., 8.]),
 array([11., 11.]),
 array([2., 8.]),
 array([15.,  7.]),
 array([ 4., 17.])]

In [25]:
PT_array = np.concatenate(PT_blocks)
PT_array

array([ 7.,  8., 11., 11.,  2.,  8., 15.,  7.,  4., 17.])

In [26]:
PT = [EAM_rev[round(i)] for i in PT_array]
PT

['h', 'i', 'l', 'l', 'c', 'i', 'p', 'h', 'e', 'r']

In [27]:
''.join(PT)

'hillcipher'